# Generated by Django 3.2.4 on 2023-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_project_management_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_researcher',
            field=models.BooleanField(default=True, verbose_name='is_researcher'),
        ),
    ]
