# Generated by Django 3.2.4 on 2023-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_is_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_researcher',
            field=models.BooleanField(default=True, verbose_name='is researcher'),
        ),
    ]
