# Generated by Django 3.2.4 on 2023-07-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userprofile_is_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_researcher',
            field=models.BooleanField(default=False, verbose_name='is researcher'),
        ),
    ]
