# Generated by Django 3.2.4 on 2022-03-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_auto_20220316_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='advisors',
        ),
        migrations.RemoveField(
            model_name='status',
            name='co_investigator',
        ),
        migrations.RemoveField(
            model_name='status',
            name='international_experts',
        ),
        migrations.RemoveField(
            model_name='status',
            name='phd_research_scholars',
        ),
        migrations.RemoveField(
            model_name='status',
            name='principle_investigator',
        ),
        migrations.RemoveField(
            model_name='status',
            name='team_members',
        ),
    ]
