# Generated by Django 3.2.4 on 2023-07-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_auto_20220318_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='estimated_completion_date',
            field=models.DateField(blank=True, max_length=100),
        ),
    ]
