# Generated by Django 3.2.4 on 2023-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0016_collaborator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='project',
        ),
        migrations.AddField(
            model_name='role',
            name='role_description',
            field=models.CharField(default='THIS', max_length=200),
            preserve_default=False,
        ),
    ]
