# Generated by Django 3.2.4 on 2023-07-15 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0017_auto_20230710_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
