# Generated by Django 3.2.4 on 2023-07-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0018_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='collborating_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to='project_management.status'),
        ),
    ]
