# Generated by Django 3.2.4 on 2023-07-10 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('research_title', models.CharField(max_length=200)),
                ('research_paper', models.FileField(blank=True, null=True, upload_to='')),
                ('link_to_project', models.URLField(blank=True, null=True)),
                ('external_researchers', models.CharField(blank=True, max_length=400, null=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('researchers', models.ManyToManyField(related_name='Publication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Publications',
                'verbose_name_plural': 'Research Publications',
            },
        ),
    ]
