# Generated by Django 3.2.4 on 2023-07-10 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_researchpublication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchpublicationlist',
            options={'verbose_name': 'Research Publications', 'verbose_name_plural': 'Research Publications'},
        ),
        migrations.AddField(
            model_name='researchpublicationlist',
            name='external_researchers',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='researchpublicationlist',
            name='link_to_project',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchpublicationlist',
            name='research_paper',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='researchpublicationlist',
            name='researchers',
            field=models.ManyToManyField(related_name='Publication', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ResearchPublication',
        ),
    ]
