# Generated by Django 3.2.4 on 2023-07-15 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_researchpublicationlist_research_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpublicationlist',
            name='_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
