# Generated by Django 3.2.4 on 2023-07-15 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_researchpublicationlist__uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpublicationlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='researchpublicationlist',
            name='published_at',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
